version: '3.9'

services:
  redis:
    image: "redis:6.2-alpine"
    container_name: redis
    command: ["redis-server", "--notify-keyspace-events", "Ex"] # for redis keyspace notification
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///../ticket_booking.db
      - RESERVATION_TIMEOUT=300  # 5 minutes
